version: '3.1'
services:
  portfolio-service:
    container_name: portfolio-service
    image: ${DOCKER_REPOSITORY}:latest
    hostname: portfolio.service
    ports:
      - "8006:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_UTILS_EXCEPTION_STACKTRACE=${SHOW_UTILS_EXCEPTION_STACKTRACE}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - CACHE_ENABLE=${CACHE_ENABLE}
      - REDIS_CACHE_ENABLE=${REDIS_CACHE_ENABLE}
      - REDIS_CACHE_PASSWORD=${REDIS_CACHE_PASSWORD}
      - REDIS_CACHE_PORT=${REDIS_CACHE_PORT}
      - REDIS_CACHE_USERNAME=${REDIS_CACHE_USERNAME}
      - REDIS_CACHE_HOST=${REDIS_CACHE_HOST}
      - APP_ENV=${APP_ENV}
      - STRAPI_AUTH_TOKEN=${STRAPI_AUTH_TOKEN}
    networks:
      docker-network:
        aliases:
          - portfolio.service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-service.rule=Host(`portfolio.service.stg.giovannilamarmora.com`)"
      - "traefik.http.services.portfolio-service.loadbalancer.server.port=8080"
      - "traefik.http.routers.portfolio-service.middlewares=corsmiddleware@file,geoblock@file"

networks:
  docker-network:
    external: true