spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

rest:
  scheduled:
    CMS:
      active: true
      locale: "it-IT,en-GB"
      cron: 0 0 1 * * MON
  client:
    contentful:
      baseUrl: https://cdn.contentful.com
      entries: /spaces/uptyiu46x1l9/environments/master/entries
      authToken: ${CONTENTFUL_AUTH_TOKEN}

app:
  logTail:
    active: false