env: ${APP_ENV:Deploy} # Used for Google Cloud LOG
spring:
  application:
    name: Portfolio Service
    starter-log: true
  data:
    cache:
      active: ${CACHE_ENABLE}
      cron: 0 0 1 * * *
    redis:
      enabled: ${REDIS_CACHE_ENABLE}
      cron: 0 0 1 * * *
      host: ${REDIS_CACHE_HOST}
      json: true
      password: ${REDIS_CACHE_PASSWORD}
      port: ${REDIS_CACHE_PORT}
      sslEnabled: false
      #sslTruststore: path of the truststore (.jks file)
      #sslTruststorePassword: password of the trustore
      username: ${REDIS_CACHE_USERNAME}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**"

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    com.giovannilamarmora.project.portfolio.PortfolioService: ${LOGGING_LEVEL}
    io.github.giovannilamarmora.utils: ${LOGGING_LEVEL}
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

rest:
  client:
    strapi:
      active: true
      baseUrl: http://app.strapi.cms:1337
      bearer: ${STRAPI_AUTH_TOKEN}
      path:
        portfolioConfig: /api/portfolio-data
        portfolioWork: /api/portfolio-works
        portfolioCourse: /api/portfolio-courses
        portfolioProject: /api/portfolio-projects

app:
  version: @project.version@ # Show Project Version
  cache:
    active: ${CACHE_ENABLE}
    cron: 0 0 1 * * *
  exception:
    stacktrace: ${SHOW_UTILS_EXCEPTION_STACKTRACE} # Active StackTrace in Response