env: ${APP_ENV:Local} # Used for Google Cloud LOG
spring:
  application:
    name: Portfolio Service
    starter-log: true
  data:
    cache:
      active: false
      cron: 0 0 1 * * *
    redis:
      enabled: false
      cron: 0 0 1 * * *
      host: pc-giovanni
      json: false
      password: password
      port: 6379
      sslEnabled: false
      #sslTruststore: path of the truststore (.jks file)
      #sslTruststorePassword: password of the trustore
      username: username

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/images/*,*/favicon.ico"

logging:
  config: classpath:logback-spring.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    com.giovannilamarmora.project.portfolio.PortfolioService: INFO
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

rest:
  client:
    strapi:
      active: true
      baseUrl: https://strapi.giovannilamarmora.com
      bearer: ${STRAPI_AUTH_TOKEN}
      path:
        portfolioConfig: /api/portfolio-data
        portfolioWork: /api/portfolio-works
        portfolioCourse: /api/portfolio-courses
        portfolioProject: /api/portfolio-projects

app:
  version: @project.version@ # Show Project Version
  exception:
    stacktrace: true # Active StackTrace in Response