env: ${APP_ENV:Deploy} # Used for Google Cloud LOG
spring:
  application:
    name: Portfolio Service
    starter-log: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/images/*,*/favicon.ico"

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    com.giovannilamarmora.project.portfolio.PortfolioService: ${LOGGING_LEVEL}
    io.github.giovannilamarmora.utils: ${LOGGING_LEVEL}
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

rest:
  scheduled:
    CMS:
      active: true
      locale: "it-IT,en-GB"
      cron: 0 0 1 * * MON
  client:
    strapi:
      active: true
      baseUrl: http://app.strapi.cms:1337
      bearer: ${STRAPI_AUTH_TOKEN}
      path:
        portfolioConfig: /api/portfolio-data
        portfolioWork: /api/portfolio-works
        portfolioCourse: /api/portfolio-courses
        portfolioProject: /api/portfolio-projects
    contentful:
      baseUrl: https://cdn.contentful.com
      entries: /spaces/uptyiu46x1l9/environments/master/entries
      authToken: ${CONTENTFUL_AUTH_TOKEN}

app:
  version: @project.version@ # Show Project Version
  shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico"
  cache:
    active: ${CACHE_ENABLE}
    cron: 0 0 1 * * *
  exception:
    stacktrace: ${SHOW_UTILS_EXCEPTION_STACKTRACE} # Active StackTrace in Response
  # Cors status
  cors: # Disabled
    enabled: false